/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL */

#ifndef _Included_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
#define _Included_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_gl_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1gl_1init
  (JNIEnv *, jclass);

/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_gl_display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1gl_1display
  (JNIEnv *, jclass);

/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_gl_reshape
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1gl_1reshape
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_gl_dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1gl_1dispose
  (JNIEnv *, jclass);

/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_mouse_click_event
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1mouse_1click_1event
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_mouse_move_event
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1mouse_1move_1event
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_mouse_drag_event
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1mouse_1drag_1event
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_mouse_press_event
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1mouse_1press_1event
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_mouse_release_event
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1mouse_1release_1event
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_mouse_enter_event
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1mouse_1enter_1event
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_mouse_exit_event
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1mouse_1exit_1event
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL
 * Method:    native_mouse_wheel_event
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vrl_v3d_nativeogl_NativeOpenGL_native_1mouse_1wheel_1event
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
